#!/bin/sh

CUPL_DEFAULT_OPTIONS="m1jn" #These are the options that will be passed to the CUPL.EXE compiled
CUPL_SIMULATION_OPTIONS="sw" #These options are added only if a .SI file is found.


#A summary of the most relevant/important options to CUPL is here. See documentation for a full list/explanation.
#
#-m1 quick minimization
# -l  create listing file
# -x create expanded product-terms in documentation file
# -f create fuse plot/chip diagram in documentation file
# -j create jedec file. If -s is specified, CSIM will append test vectors to the .JED file.
# -n use name of input file for output file
# -a create absolute file
# -b create berkeley pla format
# -e create expanded macro definitions
#
# -s run simulation. Expects a .SI file to be present, generates an .SO file. If -j is specified, will append test vectors to the .JED file. Automatically implies -a generation of an .ABS file.
# -w run simulation. Expects a .SI file to be present, genrates a .w file. Automatically inplies -a generation of an .ABS file.


RED='\033[0;31m'
NC='\033[0m' # No Color

if [ $# -ne 1 ] #Make sure we passed options to CUPL.EXE
  then
    echo "Please pass the name of a .PLD file to be compiled"
    echo "This script will attempt to compile it using CUPL.EXE"

    echo "Additionally, this script assumes you have installed WinCUPL into the default directory of c:/Wincupl,"
    echo "within the default wine prefix, and have replaced the fitters from the latest version from Atmel Prochip."
    echo "A future version might simply try to make this work without WinCUPL installation as only the CUPL compiler and the fitters are required."
    echo "For now this remains the recommended workflow and WinCUPL does come with decent examples and help files."
    exit 1
fi

FILENAME=$1

#Since CUPL.EXE accepts files without an extension, we try to do the same and append the extension if necessary.
#We're actually going through this trouble to get a true filename length.
if [ ! -f "$1" ]; then
    if [ -f "${1}.pld" ]; then
	echo "Appending .pld to input filename."
        FILENAME="$1.pld"
        continue
    fi
    if [ -f "${1}.PLD" ]; then
	echo "Appending .PLD to input filename."
        FILENAME="$1.PLD"
        continue
    fi
fi

if [ ! -f "${FILENAME}" ]; then
    echo "Cannot find file: $FILENAME"
    exit 1
fi

#Too long filenames is a horrible bug in CSIM.EXE that took forever to figure out.
if [ ${#FILENAME} -gt 19 ]; then
    printf "${RED}ERROR: Filenames longer than 19 total characters cause problems with CSIM.EXE\nUse 15 characters max for filename + 1 dot + 3 file extension.${NC}\n"
    exit 1
fi

#Multiple periods in the filename also cause CSIM.EXE to break.
if [ `echo ${FILENAME} | grep -o "\." | wc -l` -gt 1 ]; then
    printf "${RED}ERROR: Filenames containing more than one period cause problems with CSIM.EXE\nFilenames should only contain 1 period.${NC}\n"
    exit 1
fi

BASEFILENAME=${FILENAME%.*} #This strips off the file extension

#If we detect a corresponding .SI file, then we pass the -s and -w options to CUPL.EXE so that simulation is performed.
if [ -f "${BASEFILENAME}.SI" ]; then
    SIMFILENAME="${BASEFILENAME}.SI"
elif [ -f "${BASEFILENAME}.si" ]; then
    SIMFILENAME="${BASEFILENAME}.si"
else
    echo "WARNING: Corresponding .SI input file not found. Simulation / Test vector generation will not be performed."
    CUPL_SIMULATION_OPTIONS=""
fi

#We check to see if the latest known version of fitters are installed.
FIT1502PATH=`WINEDEBUG="fixme-hid" winepath -u "c:/Wincupl//WinCupl/Fitters/fit1502.exe"`
FIT1504PATH=`WINEDEBUG="fixme-hid" winepath -u "c:/Wincupl//WinCupl/Fitters/fit1504.exe"`
FIT1508PATH=`WINEDEBUG="fixme-hid" winepath -u "c:/Wincupl//WinCupl/Fitters/fit1508.exe"`

SUMFAIL=false

if [ "fbcd61cd5348b05000ccad3d0e08cf8a8fb94538" != `sha1sum $FIT1502PATH | awk '{print $1}'` ]; then
    echo "FIT1502.exe checksum failure."
    SUMFAIL=true
fi

if [ "e99b14f68fa5de131aa388503535c51ecdf31295" != `sha1sum $FIT1504PATH | awk '{print $1}'` ]; then
    echo "FIT1504.exe checksum failure."
    SUMFAIL=true
fi

if [ "5f1ef6d220466dff8ac031acbce4e7a55dfed153" != `sha1sum $FIT1508PATH | awk '{print $1}'` ]; then
    echo "FIT1508.exe checksum failure."
    SUMFAIL=true
fi

if [ $SUMFAIL = "true" ]; then
    echo "\nIt looks like you might be using the original fitters that came with WinCUPL.\nPlease extract and replace the fitters with the latest from:"
    echo "https://ww1.microchip.com/downloads/en/DeviceDoc/ProChip5.0.1.zip"
    echo "They should identify as \"Version 1918 (3-21-07)\" run from the command line:"
    exit 4
fi

#Time to run CUPL.EXE
echo "Running WinCUPL with the following command line: "
echo "c:/Wincupl/Shared/cupl.exe -${CUPL_DEFAULT_OPTIONS}${CUPL_SIMULATION_OPTIONS} -u c:/Wincupl/Shared/cupl.dl $1"
echo "\n"
WINEDEBUG="fixme-hid,fixme-ntdll" WINEPREFIX=/home/owner/.wine wine c:/Wincupl/Shared/cupl.exe -${CUPL_DEFAULT_OPTIONS}${CUPL_SIMULATION_OPTIONS} -u c:/Wincupl/Shared/cupl.dl "$1"

